name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy code to VM
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VM_HOST }}
        username: opc
        key: ${{ secrets.VM_SSH_KEY }}
        source: "."
        target: "/var/www/html/Crud_Project"

    - name: Restart Apache
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.VM_HOST }}
        username: opc
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo systemctl restart httpd
